name: vale-lint

concurrency:
  group: pullrequest-untrusted-valelint-${{ github.event.number }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Upgrade pip
        run:
          pip install --upgrade pip
      - name: Create virtual environment
        run:
          python3 -m venv env
      - name: Use virtual environment
        run:
          source env/bin/activate
      - uses: errata-ai/vale-action@reviewdog
        with:
          version: 3.12.0
          reporter: github-check
          filter_mode: file
          fail_on_error: true
          level: error
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}